### ISSUE TITLE
Create a code playground for showing the SDK

### ISSUE THREAD

**Issue by aaitor** [nevermined-io/app_docs#134]
To facilitate the integration and demonstration of the SDK we want to have a code playground where we show the basics of the SDK.

```[tasklist]
### Tasks
- [x] Create or re-use one tutorial github repo
- [x] Load the playground from that repo
- [x] Load the SDK
- [x] The user can connect Metamask
- [x] The user can list assets on testing
- [x] The user can publish something
- [x] The user can order and download something
- [ ] The playground is linked from the docs website
```

**Comment by eruizgar91** [comment]
https://codesandbox.io/p/devbox/nvm-example-h8d6gc
