### ISSUE TITLE
Prepare NVM Query Protocol to be consumed by AI developers

### ISSUE THREAD

**Issue by aaitor** [nevermined-io/app_docs#146]
```[tasklist]
### Tasks
- [x] Prepare documentation about the Query Protocol
- [x] Prepare release of payments (Python)
- [x] Prepare release of payments (Typescript)
- [ ] https://github.com/nevermined-io/app_docs/issues/145
- [x] Define a series of blog posts
- [x] Prepare Youtube summarizer repo as example
```
